// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>
#include "NetworkConfigurator.h"
#include "ConfiguratorAgents/AgentsConfiguratorManager.h"
#include "ConfiguratorAgents/agents/BLE/BLEConfiguratorAgent.h"

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)

void onCounterChange();

int counter;

BLEConfiguratorAgent BLEAgent;
AgentsConfiguratorManager ConfiguratorManager;
WiFiConnectionHandler ArduinoIoTPreferredConnection;
NetworkConfigurator NetworkConf(ConfiguratorManager, ArduinoIoTPreferredConnection);

void initProperties(){

  ArduinoCloud.addProperty(counter, READWRITE, ON_CHANGE, onCounterChange);
  ConfiguratorManager.addAgent(BLEAgent);
}


