// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <GenericConnectionHandler.h>
#include "NetworkConfigurator.h"
#include "ConfiguratorAgents/AgentsConfiguratorManager.h"
#include "ConfiguratorAgents/agents/BLE/BLEConfiguratorAgent.h"
#include "provisioning.h"

const char SSID[] = SECRET_SSID;           // Network SSID (name)
const char PASS[] = SECRET_OPTIONAL_PASS;  // Network password (use for WPA, or use as key for WEP)

void onCounterChange();

int counter;

void initProperties() {

  ArduinoCloud.addProperty(counter, READWRITE, ON_CHANGE, onCounterChange);
  ConfiguratorManager.addAgent(BLEAgent);
}

GenericConnectionHandler ArduinoIoTPreferredConnection;
NetworkConfigurator NetworkConf(ConfiguratorManager, ArduinoIoTPreferredConnection);
Provisioning ProvisioningSystem(ConfiguratorManager);
