// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <GenericConnectionHandler.h>
#include "NetworkConfigurator.h"
#include "ConfiguratorAgents/AgentsManager.h"
#include "ConfiguratorAgents/agents/BLE/BLEAgent.h"
#include "ConfiguratorAgents/agents/Serial/SerialAgent.h"
#include "ClaimingHandler.h"

void onCounterChange();

int counter;

void initProperties() {

  ArduinoCloud.addProperty(counter, READWRITE, ON_CHANGE, onCounterChange);
  AgentsManager.addAgent(BLEAgent);
  AgentsManager.addAgent(SerialAgent);
}

GenericConnectionHandler ArduinoIoTPreferredConnection;
NetworkConfiguratorClass NetworkConfigurator(AgentsManager, ArduinoIoTPreferredConnection);
ClaimingHandlerClass ClaimingHandler(AgentsManager);
