name: Compile Examples

on:
  pull_request:
    paths:
      - ".github/workflows/compile-examples.yml"
      - "library.properties"
      - "examples/**"
      - "src/**"
  push:
    paths:
      - ".github/workflows/compile-examples.yml"
      - "library.properties"
      - "examples/**"
      - "src/**"
  schedule:
    # Run every Tuesday at 8 AM UTC to catch breakage caused by changes to external resources (libraries, platforms).
    - cron: "0 8 * * TUE"
  workflow_dispatch:
  repository_dispatch:

jobs:
  build:
    name: ${{ matrix.board.fqbn }}
    runs-on: ubuntu-latest

    env:
      LIBRARIES: |
        # Install the NetworkConfigurator library from the repository
        - source-path: ./
        - name: Arduino_DebugUtils
        - source-url: https://github.com/fabik111/Arduino_ConnectionHandler.git
          version: 0314cf54593029aea05bb8c179e40a26128f7d67
        - source-url: https://github.com/arduino-libraries/ArduinoBLE.git
        - source-url: https://github.com/arduino-libraries/Arduino_CloudUtils.git
        - source-url: https://github.com/arduino-libraries/Arduino_KVStore.git
      SKETCH_PATHS: |
        - examples/NetworkConfiguratorDemo
      SKETCHES_REPORTS_PATH: sketches-reports
    strategy:
      fail-fast: false

      matrix:
        board:
          - fqbn: arduino:samd:mkrwifi1010
            type: nina
            artifact-name-suffix: arduino-samd-mkrwifi1010
          - fqbn: arduino:samd:nano_33_iot
            type: nina
            artifact-name-suffix: arduino-samd-nano_33_iot
          - fqbn: arduino:mbed_portenta:envie_m7
            type: mbed_portenta
            artifact-name-suffix: arduino-mbed_portenta-envie_m7
          - fqbn: arduino:mbed_nano:nanorp2040connect
            type: nina
            artifact-name-suffix: arduino-mbed_nano-nanorp2040connect
          - fqbn: arduino:mbed_nicla:nicla_vision
            type: mbed_nicla
            artifact-name-suffix: arduino-mbed_nicla-nicla_vision
          - fqbn: arduino:mbed_opta:opta
            type: mbed_opta
            artifact-name-suffix: arduino-mbed_opta-opta
          - fqbn: arduino:mbed_giga:giga
            type: mbed_giga
            artifact-name-suffix: arduino-mbed_giga-giga
          - fqbn: arduino:renesas_portenta:portenta_c33
            type: renesas_portenta
            artifact-name-suffix: arduino-renesas_portenta-portenta_c33
          - fqbn: arduino:renesas_uno:unor4wifi
            type: renesas_uno
            artifact-name-suffix: arduino-renesas_uno-unor4wifi


        # make board type-specific customizations to the matrix jobs
        include:
          # MKR WiFi 1010, Nano 33 IoT, Nano RP2040 Connect
          - board:
              type: nina
            platforms: |
              # Install samd and mbed_nano platform via Boards Manager
              - name: arduino:samd
              - name: arduino:mbed_nano
            libraries: |
              - name: Blues Wireless Notecard
              - source-url: https://github.com/andreagilardoni/WiFiNINA.git
                version: 31616ac5a30f6281c68f982bc39800771b2fbaeb
              - source-url: https://github.com/adafruit/Adafruit_SleepyDog.git
          # Portenta
          - board:
              type: mbed_portenta
            platforms: |
              # Install mbed_portenta platform via Boards Manager
              - name: arduino:mbed_portenta
            libraries: |
              - name: Arduino_Cellular
              - name: Blues Wireless Notecard
          # Nicla Vision
          - board:
              type: mbed_nicla
            platforms: |
              # Install mbed_nicla platform via Boards Manager
              - name: arduino:mbed_nicla
            libraries: |
              - name: Blues Wireless Notecard
          # Opta
          - board:
              type: mbed_opta
            platforms: |
              # Install mbed_opta platform via Boards Manager
              - name: arduino:mbed_opta
            libraries: |
              - name: Blues Wireless Notecard
          # GIGA
          - board:
              type: mbed_giga
            platforms: |
              # Install mbed_giga platform via Boards Manager
              - name: arduino:mbed_giga
            libraries: |
              - name: Blues Wireless Notecard
          # Portenta C33
          - board:
              type: renesas_portenta
            platforms: |
              # Install renesas_portenta platform via Boards Manager
              - name: arduino:renesas_portenta
            libraries: |
              - name: Arduino_Cellular
              - name: Blues Wireless Notecard
          # UNO R4 WiFi
          - board:
              type: renesas_uno
            platforms: |
              # Install renesas_uno platform via Boards Manager
              - name: arduino:renesas_uno
            libraries: |
              - name: Blues Wireless Notecard

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Compile examples
        uses: arduino/compile-sketches@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          platforms: ${{ matrix.platforms }}
          fqbn: ${{ matrix.board.fqbn }}
          libraries: |
            ${{ env.LIBRARIES }}
            ${{ matrix.libraries }}
          sketch-paths: |
            ${{ env.SKETCH_PATHS }}
          enable-deltas-report: 'true'
          sketches-report-path: ${{ env.SKETCHES_REPORTS_PATH }}

      - name: Save memory usage change report as artifact
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          name: sketches-report-${{ matrix.board.artifact-name-suffix }}
          path: ${{ env.SKETCHES_REPORTS_PATH }}
